### ISSUE TITLE
Arreglar para evaluar

### ISSUE THREAD

**Issue by Ediolot** [ULL-ESIT-PL-1617/tareas-iniciales-tpka#4]
Faltan un par de notas para completar la evaluación con todos los apartados prácticamente bien. Os las dejo aquí para ver si las podéis arreglar mañana antes de que cierre. Algunas son tonterías.

- Que @alu0100887686 acabe la página web
- Colocar un enlace en la página principal (junto a los demás). Que lleve al [despliegue](https://ull-esit-pl-1617.github.io/tareas-iniciales-tpka/) en gh-pages.
- El Readme.md en GitHub no coincide con el de Gitbook. Parece que [el de Gitbook](https://alu0100891782.gitbooks.io/tareas-iniciales-tpka/content/) no está actualizado.

Si estoy equivocado en algo, comentádmelo para mirarlo

**Comment by alu0100887686** [comment]
* Se ha añadido el [enlace](https://goo.gl/W2wzeP) al despliegue en gh-pages en el apartado superior "Website".
* Se ha mejorado el diseño de la página personal del usuario [alu0100887686](https://alu0100887686.github.io/), aunque no está finalizada.
* En cuanto podamos, modificaremos el README.md en Gitbook.

Muchas gracias por notificarlo @Ediolot y perdona las molestias.

**Comment by Ediolot** [comment]
Ya completé el proceso de evaluación (de todas formas se puede cambiar), no conté esos fallos, porque son bastante sencillos de arreglar, así que no hace falta modificar el README.md en Gitbook con prisa.
